<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>x.ruiz.playground.data.engineering</groupId>
  <artifactId>parent.iceberg</artifactId>
  <packaging>pom</packaging>
  <version>1.0-SNAPSHOT</version>
  <name>Iceberg Parent</name>
  <url>http://maven.apache.org</url>

  <properties>
    <java.version>17</java.version>
    <spark.version>3.5.1</spark.version>
    <scala.binary.version>2.12</scala.binary.version>
    <iceberg.version>1.7.2</iceberg.version>
  </properties>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.apache.spark</groupId>
        <artifactId>spark-sql_${scala.binary.version}</artifactId>
        <version>${spark.version}</version>
        <!-- Use <scope>provided</scope> if deploying to an existing cluster -->
      </dependency>
      <dependency>
        <groupId>org.apache.iceberg</groupId>
        <artifactId>iceberg-core</artifactId>
        <version>${iceberg.version}</version>
      </dependency>
    </dependencies>
</dependencyManagement>
</project>
